In [1]:
# 3.8 有关相关性分析的混沌
import numpy as np  # 导入库

data = np.loadtxt('data5.txt', delimiter='\t')  # 读取数据文件
x = data[:, :-1]  # 切分自变量
correlation_matrix = np.corrcoef(x, rowvar=0)  # 相关性分析
print (correlation_matrix.round(2))  # 打印输出相关性结果

[[ 1.   -0.04  0.27 -0.05  0.21 -0.05  0.19 -0.03 -0.02]
 [-0.04  1.   -0.01  0.73 -0.01  0.62  0.    0.48  0.51]
 [ 0.27 -0.01  1.   -0.01  0.72 -0.    0.65  0.01  0.02]
 [-0.05  0.73 -0.01  1.    0.01  0.88  0.01  0.7   0.72]
 [ 0.21 -0.01  0.72  0.01  1.    0.02  0.91  0.03  0.03]
 [-0.05  0.62 -0.    0.88  0.02  1.    0.03  0.83  0.82]
 [ 0.19  0.    0.65  0.01  0.91  0.03  1.    0.03  0.03]
 [-0.03  0.48  0.01  0.7   0.03  0.83  0.03  1.    0.71]
 [-0.02  0.51  0.02  0.72  0.03  0.82  0.03  0.71  1.  ]]


In [5]:
import pandas as pd
pd.DataFrame(data).corr()

0         1         2         3         4         5         6  \
0  1.000000 -0.039381  0.270272 -0.046812  0.212352 -0.049654  0.194946   
1 -0.039381  1.000000 -0.010267  0.728366 -0.005079  0.623580  0.002037   
2  0.270272 -0.010267  1.000000 -0.010051  0.717708 -0.000572  0.653531   
3 -0.046812  0.728366 -0.010051  1.000000  0.008142  0.875770  0.011656   
4  0.212352 -0.005079  0.717708  0.008142  1.000000  0.018976  0.914978   
5 -0.049654  0.623580 -0.000572  0.875770  0.018976  1.000000  0.027437   
6  0.194946  0.002037  0.653531  0.011656  0.914978  0.027437  1.000000   
7 -0.029388  0.480135  0.010562  0.702587  0.027393  0.827199  0.030520   
8 -0.023825  0.509560  0.024606  0.718845  0.029371  0.824765  0.034807   
9  0.949789 -0.043393  0.279107 -0.051305  0.205769 -0.049614  0.181873   

          7         8         9  
0 -0.029388 -0.023825  0.949789  
1  0.480135  0.509560 -0.043393  
2  0.010562  0.024606  0.279107  
3  0.702587  0.718845 -0.051305  
4  0.027393  0.029371  0.205769  
5  0.827199  0.824765 -0.049614  
6  0.030520  0.034807  0.181873  
7  1.000000  0.712789 -0.039132  
8  0.712789  1.000000 -0.024950  
9 -0.039132 -0.024950  1.000000